env:
  contexts:
  - name: Authentication Test
    urls:
    - https://www.periplus.com
    includePaths:
    - https://www.periplus.com.*
    excludePaths:
    - https://www.periplus.com.*.css
    - https://www.periplus.com.*.mp3
    - https://www.periplus.com.*.mp4
    - https://www.periplus.com.*.jpg
    - https://www.periplus.com.*.jpeg
    - https://www.periplus.com.*.woff
    - https://www.periplus.com.*.webp
    - https://www.periplus.com.*.png
    - https://www.periplus.com.*.svg
    authentication:
      method: form
      parameters:
        loginPageUrl: https://www.periplus.com/account/Login
        loginRequestUrl: https://www.periplus.com/account/Login
        loginRequestBody: "email={%username%}&password={%password%}"
      verification:
        method: autodetect
        loggedOutRegex: <input type="submit" value="Login" id="button-login">
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: cookie
    technology: {}
    structure: {}
    users:
    - name: gabriella
      credentials:
        password: mypassword
        username: naomi@gmail.com
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: spider
  parameters:
    context: Authentication Test
    user: gabriella
    url: https://www.periplus.com/
    parseDsStore: null
- type: spiderAjax
  parameters:
    context: Authentication Test
    user: gabriella
    url: https://www.periplus.com/
    browserId: null
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters:
    context: Authentication Test
    user: gabriella
  policyDefinition:
    defaultStrength: insane
    defaultThreshold: high
