env:
  contexts:
  - name: Authentication Test
    urls:
    - http://54.179.2.8:4001
    includePaths:
    - http://54.179.2.8:4001.*
    excludePaths:
    - http://54.179.2.8:4001.*.css
    - http://54.179.2.8:4001.*.mp3
    - http://54.179.2.8:4001.*.mp4
    - http://54.179.2.8:4001.*.jpg
    - http://54.179.2.8:4001.*.jpeg
    - http://54.179.2.8:4001.*.woff
    - http://54.179.2.8:4001.*.webp
    - http://54.179.2.8:4001.*.png
    - http://54.179.2.8:4001.*.svg
    authentication:
      method: form
      parameters:
        loginPageUrl: http://54.179.2.8:4001/login
        loginRequestUrl: http://54.179.2.8:4001/login
        loginRequestBody: "email={%username%}&password={%password%}"
      verification:
        method: autodetect
        loggedOutRegex: <input type="submit">
        pollFrequency: 60
        pollUnits: requests
        pollUrl: ""
        pollPostData: ""
    sessionManagement:
      method: cookie
    technology: {}
    structure: {}
    users:
    - name: rajif
      credentials:
        password: mypassword
        username: rajif@gmail.com
  parameters: {}
jobs:
- type: passiveScan-config
  parameters: {}
- type: spider
  parameters:
    context: Authentication Test
    user: rajif
    url: http://54.179.2.8:4001/
    parseDsStore: null
- type: spiderAjax
  parameters:
    context: Authentication Test
    user: rajif
    url: http://54.179.2.8:4001/
    browserId: null
- type: passiveScan-wait
  parameters: {}
- type: activeScan
  parameters:
    context: Authentication Test
    user: rajif
  policyDefinition:
    defaultStrength: insane
    defaultThreshold: high
